(()=>{
  const seen=new WeakSet();
  const parseCount=value=>{const s=String(value??'').trim().toLowerCase().replace(/,/g,'');const m=s.match(/([\d.]+)\s*(万|w|k)?/);if(!m)return 0;const n=Number(m[1])||0;return Math.round(n*((m[2]==='万'||m[2]==='w')?10000:m[2]==='k'?1000:1))};
  const stripHtml=s=>{const d=document.createElement('div');d.innerHTML=String(s??'');return (d.innerText||d.textContent||'').trim()};
  const normalizeUser=raw=>{const id=raw?.id??raw?.user_id??raw?.uid;const nickname=raw?.screen_name??raw?.name??raw?.nickname;const followers=parseCount(raw?.followers_count??raw?.followers??raw?.fans_count??0);if(!id||!nickname)return null;return{xueqiu_user_id:String(id),nickname:String(nickname),followers_count:followers,profile_url:`https://xueqiu.com/u/${id}`,avatar_url:String(raw?.profile_image_url??raw?.avatar??''),verified_description:String(raw?.verified_description??raw?.verified_desc??''),description:String(raw?.description??raw?.intro??''),primary_topics:[],representative_content:'',source_label:`雪球页面：${document.title}`}};
  const normalizePost=raw=>{const id=raw?.id??raw?.status_id;const userId=raw?.user_id??raw?.user?.id??raw?.uid;if(!id||!userId)return null;return{xueqiu_post_id:String(id),xueqiu_user_id:String(userId),author_nickname:String(raw?.user?.screen_name??raw?.screen_name??raw?.author_nickname??''),author_avatar_url:String(raw?.user?.profile_image_url??raw?.profile_image_url??''),body:stripHtml(raw?.text??raw?.description??raw?.body??''),created_at_xueqiu:raw?.created_at?new Date(Number(raw.created_at)).toISOString():null,like_count:parseCount(raw?.like_count??raw?.fav_count??0),comment_count:parseCount(raw?.reply_count??raw?.comment_count??0),retweet_count:parseCount(raw?.retweet_count??raw?.share_count??0),source_url:String(raw?.target??raw?.source_url??`https://xueqiu.com/${userId}/${id}`),reply_to_nickname:String(raw?.reply_screen_name??''),quoted_body:stripHtml(raw?.retweeted_status?.text??raw?.quoted_body??''),raw_payload:{}}};
  function walk(value,users,posts,depth=0){if(!value||depth>8)return;if(typeof value!=='object')return;if(seen.has(value))return;seen.add(value);const u=normalizeUser(value);if(u)users.set(u.xueqiu_user_id,u);const p=normalizePost(value);if(p&&p.body)posts.set(p.xueqiu_post_id,p);if(Array.isArray(value)){for(const x of value)walk(x,users,posts,depth+1)}else{for(const x of Object.values(value))walk(x,users,posts,depth+1)}}
  function scanScripts(users,posts){for(const script of document.scripts){const txt=script.textContent||'';if(txt.length<20||txt.length>6000000)continue;const candidates=[];if(script.type==='application/json')candidates.push(txt);const idx=txt.indexOf('{');const end=txt.lastIndexOf('}');if(idx>=0&&end>idx)candidates.push(txt.slice(idx,end+1));for(const c of candidates){try{walk(JSON.parse(c),users,posts)}catch{}}}}
  function scanDom(users,posts){
    for(const a of document.querySelectorAll('a[href*="/u/"]')){const m=(a.getAttribute('href')||'').match(/\/u\/(\d+)/);if(!m)continue;const id=m[1],container=a.closest('article,li,[class*=user],[class*=card],[class*=status]')||a.parentElement;const text=(container?.innerText||a.innerText||'').trim();const nickname=(a.getAttribute('title')||a.innerText||'').trim().replace(/^@/,'');const img=container?.querySelector('img')?.src||'';const fanMatch=text.match(/(?:粉丝|关注者)\s*([\d,.万wk]+)/i);const followers=fanMatch?parseCount(fanMatch[1]):0;const existing=users.get(id)||{xueqiu_user_id:id,nickname:nickname||`雪球用户${id}`,followers_count:followers,profile_url:`https://xueqiu.com/u/${id}`,avatar_url:img,verified_description:'',description:'',primary_topics:[],representative_content:'',source_label:`雪球页面：${document.title}`};if(followers>existing.followers_count)existing.followers_count=followers;if(nickname)existing.nickname=nickname;if(img)existing.avatar_url=img;users.set(id,existing)}
    const statusSelectors=['article','[class*=status-item]','[class*=timeline__item]','[class*=feed-item]','[data-id]'];
    for(const node of document.querySelectorAll(statusSelectors.join(','))){const link=node.querySelector('a[href*="/"]');const href=link?.href||'';const m=href.match(/xueqiu\.com\/(?:u\/)?(\d+)\/(\d+)/);if(!m)continue;const [_,uid,pid]=m;const body=(node.querySelector('[class*=text],[class*=content],[class*=description]')?.innerText||node.innerText||'').trim();if(body.length<10)continue;const author=node.querySelector('a[href*="/u/"]')?.innerText?.trim().replace(/^@/,'')||'';const counts=[...node.querySelectorAll('button,span,a')].map(x=>x.innerText.trim());const get=(key)=>{const t=counts.find(x=>x.includes(key));return t?parseCount(t.replace(key,'')):0};posts.set(pid,{xueqiu_post_id:pid,xueqiu_user_id:uid,author_nickname:author,author_avatar_url:node.querySelector('img')?.src||'',body:body.slice(0,12000),created_at_xueqiu:null,like_count:get('赞'),comment_count:get('评论'),retweet_count:get('转发'),source_url:href,reply_to_nickname:'',quoted_body:'',raw_payload:{source:'dom'}})}
  }
  function mergePostUsers(users,posts){for(const p of posts.values()){if(!users.has(p.xueqiu_user_id)){users.set(p.xueqiu_user_id,{xueqiu_user_id:p.xueqiu_user_id,nickname:p.author_nickname||`雪球用户${p.xueqiu_user_id}`,followers_count:0,profile_url:`https://xueqiu.com/u/${p.xueqiu_user_id}`,avatar_url:p.author_avatar_url||'',verified_description:'',description:'',primary_topics:[],representative_content:p.body.slice(0,500),source_label:`雪球页面：${document.title}`})}}}
  async function scan(){seen.clear?.();const users=new Map(),posts=new Map();scanScripts(users,posts);scanDom(users,posts);mergePostUsers(users,posts);return{users:[...users.values()],posts:[...posts.values()],page:{title:document.title,url:location.href}}}
  chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{if(message?.type!=='SCAN_XUEQIU')return;scan().then(sendResponse).catch(e=>sendResponse({error:e.message}));return true});
})();